/**
 * User space driver API for sunwave's fingerprint device.
 * ATTENTION: Do NOT edit this file unless the corresponding driver changed.
 *
 * Copyright (C) 2016 Sunwave Corporation. <http://www.sunwavecorp.com>
 * Copyright (C) 2016 Langson Leung <mailto:liangzh@sunwavecorp.com>
 *
 * This program is free software; you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free 
 * Software Foundation; either version 2 of the License, or (at your option) 
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General 
 * Public License for more details.
**/

#ifndef __SF_CTRL_API_H__
#define __SF_CTRL_API_H__

/* Device node. */
#define SF_CTL_DEV_NAME "/dev/sunwave_fp"

/* Max driver version buffer length. */
#define SF_DRV_VERSION_LEN 32

typedef enum {
    SF_KEY_NONE = 0,
    SF_KEY_HOME,
    SF_KEY_MENU,
    SF_KEY_BACK,
} sf_key_type_t;

typedef struct {
    sf_key_type_t key;
    int value; /* for key type, 0 means up, 1 means down. */
} sf_key_event_t;

#define SF_IOCTL_MAGIC 's' // 0x73

#define SF_IOCTL_RESET_DEVICE      _IO (SF_IOCTL_MAGIC, 0x01)
#define SF_IOCTL_REPORT_KEY_EVENT  _IOW(SF_IOCTL_MAGIC, 0x02, sf_key_event_t *)
#define SF_IOCTL_GET_VERSION       _IOR(SF_IOCTL_MAGIC, 0x20, const char *)

/*//////////////////////////////////////////////////////////////////////////////
#define SF_IOCTL_WRITE      _IOW (SF_IOCTL_MAGIC, 0x0x, unsigned int)
#define SF_IOCTL_READ       _IOR (SF_IOCTL_MAGIC, 0x0y, unsigned int)
#define SF_IOCTL_WRITE_READ _IOWR(SF_IOCTL_MAGIC, 0x0z, unsigned int)
//////////////////////////////////////////////////////////////////////////////*/

#endif /* __SF_CTRL_API_H__ */

