ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/mach/
ccflags-y += -I$(srctree)/drivers/spi/mediatek/mt6735
ccflags-y += -I$(srctree)/drivers/misc/mediatek/fingerprint/inc/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/teei/V1.0/tz_driver/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/teei/V1.0/tz_vfs

#ccflags-$(CONFIG_FINGERPRINT_USING_EXT_LDO) += -DFINGERPRINT_USING_EXT_LDO
#ccflags-$(CONFIG_FINGERPRINT_VGP1_POWER) += -DFINGERPRINT_VGP1_POWER
#ccflags-$(CONFIG_FINGERPRINT_SW9051) += -DCONFIG_FINGERPRINT_SW9051
obj-y			:= sf_ctl.o sf_spi.o


