#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += ili9881d_hd720_dsi_vdo_ykl_cpt_ips_b50028.o


ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc


