include $(srctree)/drivers/misc/mediatek/Makefile.custom
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/$(subst ",,$(CONFIG_MTK_PLATFORM))/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/sound/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/sound/inc

obj-y	+=  yusu_android_speaker.o